### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#1]
- [x] Translate messages to English.
- [ ] Translate or don't use hints (for country, locality, etc.).
- [x] Translate routes to English. Set canonical metatags?
- [x] Expose language option in user preferences.
- [x] Translate license and readme to English.
- [x] Translate issue templates to English.
- [ ] Translate URLs to English in tests.

**Comment by TomaszGasior** [comment]
@HyperDX @NightPurrer @SzymonDX

W najnowszej wersji 3.23 (którą prawdopodobnie wrzucę na radiolista.pl jutro, jeśli będę w stanie) będzie miała wsparcie dla języka angielskiego w interfejsie. Będę bardzo wdzięczny, jeśli rzucicie okiem na tłumaczenia pojęć technicznych. Jeśli mielibyście taką ochotę, już teraz możecie z tłumaczeniami znajdującymi się w tym folderze: https://github.com/TomaszGasior/RadioLista-v3/tree/master/translations Wszelkie odnalezione błędy proszę zgłosić w tym wątku, tutaj.

**Comment by HyperDX** [comment]
Jakoś nie pasuje mi użyte w RL określenie "list" w odniesieniu do wykazu. Myślę, że lepiej pasowałoby tu słowo "log"używane dość często przez DXerów w odniesieniu do wykazu. Przykładowo: http://fm-dx-logs.byethost24.com/tropo.htm?i=1 https://konrad.fmdx.pl/ https://lukasz.fmdx.pl/ http://dxinfocentre.com/hepburn/dxlogs/dxtv.htm czy też w moim wykazie ;)

**Comment by TomaszGasior** [comment]
> Jakoś nie pasuje mi użyte w RL określenie "list" w odniesieniu do wykazu. Myślę, że lepiej pasowałoby tu słowo "log"używane dość często przez DXerów w odniesieniu do wykazu. Przykładowo: http://fm-dx-logs.byethost24.com/tropo.htm?i=1 https://konrad.fmdx.pl/ https://lukasz.fmdx.pl/ http://dxinfocentre.com/hepburn/dxlogs/dxtv.htm czy też w moim wykazie ;)

Sprawdziłem sobie znaczenie słowa „log” w słowniku google i nie dostałem żadnej użytecznej informacji. Zgodnie z moimi oczekiwaniami, słownik Microsoft podaje „dziennik”, co ma dużo sensu i w odniesieniu np. do logów w komputerach i w przypadku np. bandscanu. 

Nie zamierzam podważać twojej wiedzy, ani wiedzy zalinkowanych autorów. :) Natomiast problem jaki widzę w tym słowie jest taki, że zależy mi na tym, aby RadioLista była miejscem nie tylko dla radiowców z prawdziwego zdarzenia, pełnych pasji fachowców tworzących bandscany i uzupełniających polaryzację i mod nadajnika. Chcę żeby była tez fajnym miejscem, dla userów takich jak ja sam, tzn. „casualowych” słuchaczy radia, którzy chcą sobie zrobić nomen omen właśnie **listę** stacji zapisanych w odbiorniku albo ulubionych — to tez zaznaczam np. na stronie głównej w opisie. 

Wydaje mi się więc, że słowo „list” jest takie bardziej ogólne i zrozumiałe dla każdego. Innymi słowy „log” traktuję jako specyficzny rodzaj „list”, ale chcę żeby RL była tez dobra jakie miejsce dla innych rodzajów „list”, nie tylko „log”. Oczywiście jestem zainteresowany twoim zdaniem. :)
