### ISSUE TITLE
Introduce channel column

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#122]
Requested in #146

**Comment by HyperDX** [comment]
As you can see here:
https://www.sat-charts.eu/artykul,2092,Raster-czestotliwosciowy-kanalow-DAB-(pasmo-VHF).html
Channel column contains number and letter from 5A to 13F. Frequency column can be automatically filled for example if you choose channel 12A column with frequency will show 223,936 MHz and you don't have to fill it manually :)
