### ISSUE TITLE
Problem z dodawaniem nowych stacji

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#151]
Dość poważny problem, który powstał pewnie przypadkowo w skutek ostatniej aktualizacji. Nie można dodać nowej stacji z innego zakresu niż DAB ponieważ pole z numerem kanału DAB jest wymagane, aby dodać nową pozycję. Przez to dodawanie stacji FM/AM jest **niemożliwe** nawet, gdy kolumna z kanałem DAB jest ukryta.

Quite serious issue that was caused by last update (3.31). You **can't add** new station (for example from FM/AM band) other than this from DAB band because defined DAB channel is required to add a new item even if the collumn is hidden.

**Comment by TomaszGasior** [comment]
Dzięki. Naprawione. :)
