### ISSUE TITLE
Tabs and fields: Screenreader reading ewerything in the first field

### ISSUE THREAD

**Issue by NightPurrer** [TomaszGasior/RadioLista-v3#155]
Tested with newest version of NVDA 2021.1.
When i step on the first field in selected category eg. "Broadcast and content"
The screenreader reads all fields one by one. It looks like:
"Broadcast and content Transmitter location Transmitter power kW Transmitter polarization (no information) Digital multiplex DAB channel (no information) Content type music Content locality nationwide  zakładka"
NVDA reads Zakładka (Tab) but it's a text field of the "Transmitter location" option, where i can start writing.
To read the name of the first column correctly, press tab and then shift+tab to back.

**Comment by TomaszGasior** [comment]
To be honest, I don't understand exactly what's wrong in behavior you described. I will try to reproduce this behavior in Windows with NVDA when I will find free time and then I will ask more questions if it will be needed. Thanks for reporting the issue, although.

**Comment by NightPurrer** [comment]
I will record what's wrong and add the audio recording.
PL:
W pierwszym polu tekstowym każdej podkategorii miast odczytać jego nazwę, NVDA odczytuje wszystkie następne i błędnie określa je jako zakładkę.
Aby odczytać wyłącznie jego nazwę, należy nacisnąć tab, przechodząc do kolejnego pola, i cofnąć się do niego klawiszami shift+tab. W tedy zostanie odczytana tylko nazwa i zostanie ono rozpoznane poprawnie jako pole tekstowe.

**Comment by TomaszGasior** [comment]
Thank you for your bug report. Indeed, I reproduced your problem with both NVDA on Windows and Orca on Fedora Linux. I've just pushed fixed version to the radiolista.pl. I hope the issue is now resolved. :)

**Comment by NightPurrer** [comment]
Thanks :) i checked and it works properly!
