### ISSUE TITLE
Editable URLs in radiostation comments

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#2]
User suggestion:

> Mam pomysł odnośnie Radiolisty. Czy można dodać takie coś, że w polu "Komentarz" można dodać link z odbioru. Nie chodzi mi o wklejanie całego długiego linku do komentarza, lecz zrobienie tego jako hiperłącze. Czy jest możliwość, aby taka funkcja powstała?

This could be implemented by replacing plain textarea field with CKEditor instance and rendering raw HTML in radiotable row. This change might allow users to use basic formatting in radiostation comment.  That CKEditor instance would have to use separate settings because paragraphs does not make sense inside table cell. Also, additional server side validation might be needed.

**Comment by TomaszGasior** [comment]
Scatter jest najczęściej używanym określeniem, a w języku polskim "rozproszenie troposferyczne" nie brzmi zbyt dobrze. Tak dla pojedynczych ;).

**Comment by TomaszGasior** [comment]
http://forum.radiopolska.pl/index.php?showtopic=20778&view=findpost&p=407274

**Comment by HyperDX** [comment]
Mam jeszcze jeden pomysł odnośnie pola z dokumentacją odbioru. Może nie jako hiperłącze, ale osobna kolumna z ikonką w stylu przycisku "Play", która przenosi nas do dokumentacji odbioru np. filmiku, zdjęcia.

**Comment by TomaszGasior** [comment]
> Mam jeszcze jeden pomysł odnośnie pola z dokumentacją odbioru. Może nie jako hiperłącze, ale osobna kolumna z ikonką w stylu przycisku "Play", która przenosi nas do dokumentacji odbioru np. filmiku, zdjęcia.

Zgłoś to proszę jako oddzielne pole. Dzięki!

**Comment by TomaszGasior** [comment]
In my opinion this feature will be completely unneeded if https://github.com/TomaszGasior/RadioLista-v3/issues/30 will be implemented. For now I will mark this one as WONTFIX but feel free to reopen and comment if you don't agree.
