### ISSUE TITLE
Manual radiotable width

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#21]
User suggestion:
>  Ja jeszcze bym sugerował opcję ręcznego ustawienia szerokości strony. Aktualnie albo można korzystać z zdefiniowanej szerokości (dla mnie zbyt wąskie) albo rozciągnąć wykaz na całą szerokość strony (a to za szerokie).

**Comment by TomaszGasior** [comment]
TODO:

- **Investigate whether this feature is really needed.**   
Personally I dislike it because it would make UI of radiotable settings less readable. Also, I don't think it would be really useful — for me, current options: full width and website default width are sufficient.   
**Feel free to comment this issue and discuss this stuff if you don't agree with me! :)**
- Implement the feature itself — seems to be simple.
- Design new UI for appearance settings of radiotable:
  - Disable (but not hide) custom theme specific settings when built-in theme is used. Solve strange problems with jscolor widget not working properly on disabled field.
  - Offer three width options: full width, default width, custom width. New custom Sf4 form types or custom form theme might be needed.

**Comment by HyperDX** [comment]
I have an idea. When you double click on the of the column (on the edge of two columns) it will adjust automatically width of the selected column or you can also change it manually by dragging column on top like in Excel.

**Comment by TomaszGasior** [comment]
> I have an idea. When you double click on the of the column (on the edge of two columns) it will adjust automatically width of the selected column or you can also change it manually by dragging column on top like in Excel.

Currently I don't have any plans for this kind of feature. However, I am in progress of implementing manual radio table width.
