### ISSUE TITLE
Brak możliwości edycji opisu wykazu przy użyciu NVDA

### ISSUE THREAD

**Issue by NightPurrer** [TomaszGasior/RadioLista-v3#229]
W ustawieniach chcąc przeedytować opis przy użyciu Screenreadera nie mogę tego zrobić. Jest tylko informacja Opis wykazu i nic po za tym.

**Comment by TomaszGasior** [comment]
Problem nie jest związany z czytnikiem ekranowym. W wyniku usterki technicznej edytor opisu wykazu/profilu przestał dzialać wcale, również dla osób niekorzystających z czytnika. Problem zostanie za chwilę rozwiązany.
