### ISSUE TITLE
Add radiostation field: max. signal level

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#25]
User suggestions:

>  Można też dodać dodatkową kolumnę z maksymalnym zanotowanym sygnałem. Jednostki do wyboru mogą być takie jak: dB, dBf, dBµV, dBm (wybierane z listy podczas dodawania, lub ustawiane jako domyślne w ustawieniach).

>  Co do kolumny to może ona się nazywać tak jak wybrana jednostka, albo to samo z przedrostkiem max.

**Comment by TomaszGasior** [comment]
User suggestion:

>  Myślę, że "max sig" lub "max signal" będzie odpowiednim zwrotem. Co do wartości ja bym tam dał od 1-150 (niektórzy mieszkają tak blisko obiektu, że pewnie sygnał jest aż tak wysoki więc taki przedział). Zero miejsc po przecinku (czyli np. 10 dBf) no chyba, że ktoś by chciał bardzo dokładnie notować sygnał, ale raczej nie sądzę.

**Comment by TomaszGasior** [comment]
@HyperDx czym różnią sie te jednostki — dB, dBf, dBµV, dBm? Czy każda z nich jest niezbędna, czy można zamiast niej po prostu użyć jednej z góry określonej?

**Comment by HyperDX** [comment]
Otóż dB jako jednostka sygnału jest nieprawidłowa (chyba, że jest to dB S/N jak w popularnych tunerach Sony). dB musi mieć odniesienie do czegoś. dBf - do femtowata, dBµV - do mikrowolta dBm - do mikrowata. Każda się od siebie różni. Można o tym przeczytać tu: [https://en.wikipedia.org/wiki/Decibel#Radio_power,_energy,_and_field_strength](url) . Jeśli nie da się dodać kolumny, której nazwa będzie zależała od wybranej przez użytkownika jednostki to można najwyżej nazwać ją po prostu max. sig, a użytkownik poinformuje na samym dole w opisie jakiej jednostki używa. Bez sensu jest też dopisywanie w każdym wierszu przy każdym sygnale wybraną jednostkę np. 60 dBf, 52 dBf tylko po prostu 60, 52. Sama kolumna mogłaby nazywać się max.sig [] (w nawiasie kwadratowym wybrana przez użytkownika jednostka). Co do samego pola, nie będzie szerokie 3 cyfry jedynie. Bez przecinków, myślę, że są one nie potrzebne.

**Comment by TomaszGasior** [comment]
To w takim razie skoro dB jest niepoprawne w tym kontekście to może opcje dBf, dBµV, dBm powinny wystarczyć?

**Comment by HyperDX** [comment]
Ja bym zostawił tylko pod jednym względem. Użytkownicy starych tunerów Sony (również kiedyś ja) mają wyświetlany sygnał w postaci "dB" pod różnymi względami jest to nieprawidłowe oznaczenie, ale obstawiam, że osoby korzystające z tych tunerów i ustawiające w ustawieniach wykazu swoją jednostkę sygnału będą miały problem, bo jej tam nie ma, niby niepoprawne, ale ja bym zostawił chociaż dla użytkowników tych tunerów.

**Comment by TomaszGasior** [comment]
Ok. Postaram się zaimplementować tę kolumnę wraz z wyborem jednostki, ale na pewno po v3.10 — w niej będą już dwie nowe. :)

**Comment by TomaszGasior** [comment]
@HyperDX  Czy ta kolumna powinna być twoim zdaniem domyslnie widoczna  w nowych wykazach?

**Comment by TomaszGasior** [comment]
@HyperDX No i jeszcze drugie pytanie: która z tych jednostek — dB, dBf, dBµV, dBm — jest najpopularniejsza i tym samym powinna być domyślna po utworzeniu wykazu?

**Comment by HyperDX** [comment]
1. Myślę, że powinna być domyślnie ukryta, tylko nieliczne odbiorniki są wyposażone w wskaźnik poziomu sygnału.

2. Myślę, że tutaj dBf jest jednostką najpopularniejszą i powinna ona być jako domyślna ;).

**Comment by TomaszGasior** [comment]
Dzięki, postaram się dzisiaj wrzucić nową wersję.

**Comment by HyperDX** [comment]
Dzięki za nową funkcję, ale chciałbym nadmienić iż dBm nie może być dodatnie jedynie ujemne ;).

**Comment by TomaszGasior** [comment]
Ups, cięzko to będzie teraz naprawić.

**Comment by TomaszGasior** [comment]
W wersji v3.20 w poprawce https://github.com/TomaszGasior/RadioLista-v3/commit/3a429cc8d20be25e196ee2b3941969c259ec0b25 usunąłem możliwość użycia jednostki dBm. 

**Następnym razem proszę o bardziej skrupulatne precyzowanie propozycji nowych funkcji.**   
Naprawianie tego typu rzeczy na *już wprowadzonych* przez użytkowników danych bywa uciążliwe i powoduje niepotrzebną stratę czasu.

W takim razie proszę o doprecyzowanie: które jednostki przyjmują wartości dodatnie, ujemne, dodatnie i ujemne?

**Comment by HyperDX** [comment]
Kurczę myślałem, że o tym wspomniałem, no cóż mój błąd.
A jednak wspominałem: [https://forum.radiopolska.pl/index.php?showtopic=20778&st=197](url) ;).
Wartości ujemne tylko dla dBuV (ujemne i dodatnie) i dBm.
Jeśli chodzi o zakresy to dla dBuV może to być od -10 do 80 dBuV
dBm od -120 do -20
dBf od 0 do 140
dB jak wyżej
Oczywiście wartości najwyższe, które wymieniłem dotyczą raczej tylko osób, które mieszkają dosłownie pod obiektem i sygnał z tych obiektów jest mega mocny. ;)

**Comment by TomaszGasior** [comment]
Trochę tych komentarzy było. To w takim razie zrobimy po prostu tak, że wybór jednostki będzie oddzielnie, a reguła walidacji będzie pozwalała na wprowadzanie wartości i ujemnych, i dodatnich, bez limitu. Postaram się dzisiaj wrzucić taką poprawkę.

**Comment by TomaszGasior** [comment]
@HyperDX  zrobione, dzięki.
