### ISSUE TITLE
Change Polish title of first log date column

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#26]
Current title "Odbiór od" is semantically incorrect but short.

User's suggestions:
- odbierane od
- data RX
- 1st log

User's notices:

>  Niekoniecznie 'odbierane od' czy też aktualne "odbiór od" ma sens. Przykładowo u mnie większość wykazu to jednak spis osiągów troposferycznych. A stacje odbierane stale są pogrubione (w moim przypadku).

>  No właśnie - problem w tym, że angielska nazwa "1st log" brzmi tu najlepiej. A polski odpowiednik "pierwszy odbiór" już niekoniecznie.

**Comment by HyperDX** [comment]
In my opinion 1st log is the best term of first time reception. I know that RadioLista is in Polish but we don't have any term as good as 1st log, in Polish language.

**Comment by TomaszGasior** [comment]
Now, I think that "1. odbiór" will be the best solution semantically.
