### ISSUE TITLE
Ugly columns jumping when loading long radiotable

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#29]
New smart mechanism of number indent introduced in https://github.com/TomaszGasior/RadioLista-v3/commit/b70975f580bd5fa3e74af85f7a207faca9a2232b (v3.6) causes ugly jumps when page is loaded, especially in Chrome. Let's optimize it!

**Comment by TomaszGasior** [comment]
After some investigation I understood that this problem occurred even in RLv2 so it's not related to new number indent algorithm.  It's probably caused by big amount of table rows and it appears in all browser when page is loaded first time (the biggest effect is in Chrome) but only in Chrome when page is loaded second time.

Example radiotable: https://radiolista.pl/wykaz/6

**Comment by TomaszGasior** [comment]
It seems to me that the issue is related to the way how browsers render tables, especially tables with non-fixed column widths. The only possible solution which I see now is to make columns width fixed but I don't want to do it and I prefer to use auto width for better readability.

**Comment by HyperDX** [comment]
On the newest version of Mozilla Firefox this bug doesn't exist

**Comment by TomaszGasior** [comment]
Yep, bug occurs in all browsers only on first page load (you probably didn't notice) and always (on each page reload) in Chrome.

**Comment by TomaszGasior** [comment]
In my honest opinion this bug is caused by the way how browsers (especially Chrome) optimize rendering of table (especially long tables) and I don't have idea what to do with it.
