### ISSUE TITLE
Nowe pole stacji radiowej: dokumentacja odbioru

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#30]
Mam jeszcze jeden pomysł odnośnie pola z dokumentacją odbioru. Może nie jako hiperłącze, ale osobna kolumna z ikonką w stylu przycisku "Play", która przenosi nas do dokumentacji odbioru np. filmiku, zdjęcia.

**Comment by TomaszGasior** [comment]
Jeszcze uściślijmy. Pole ma dotyczyć całego wykazu (i pokazywać się np. w opisie pod wykazem) czy ma być to oddzielne pole dla każdej stacji oddzielnie? 
(Szkoda, że nie użyłeś szablonu zgłoszenia — tam było takie pole. :) )

**Comment by HyperDX** [comment]
Szybko wkleiłem i nie zauważyłem szablonu. Następnym razem będę o nim pamiętać!

Oddzielne pole dla każdej stacji. Tak jak jest to przedstawione tutaj: [https://konrad.fmdx.pl/](url)

**Comment by TomaszGasior** [comment]
Zaimplementowałem w https://github.com/TomaszGasior/RadioLista-v3/commit/3c3c6fb737589f8a98d7c33cf0472b0a008aab3b. Zamierzam wrzucić do RLv3.10. Co o tym sądzisz, @HyperDX ?

![Zrzut ekranu z 2019-07-19 02-41-21](https://user-images.githubusercontent.com/1395027/61501436-9d116c80-a9cf-11e9-89ff-1033f1a255d4.png)

![Zrzut ekranu z 2019-07-19 02-42-10](https://user-images.githubusercontent.com/1395027/61501442-a39fe400-a9cf-11e9-9320-7742538f344c.png)

**Comment by HyperDX** [comment]
Super o to dokładnie mi chodziło! Dzięki!
