### ISSUE TITLE
[RDS PS] Dzielenie na linie tekstu

### ISSUE THREAD

**Issue by SzymonDX** [TomaszGasior/RadioLista-v3#31]
Proponuję nowy widok RDS PS w wykazie - a dokładniej dzielenie na linie tekstu, według upodobania użytkownika. Przykładowo:
linia 1: > ESKA < | Wroclaw_ | [zespol]
linia 2: > ESKA < | Wroclaw_ | 104.9_FM

Identyczne rozwiązanie jest zastosowane w wykazie RadioPolski, np. [http://radiopolska.pl/wykaz/fm/401](url)

**Comment by TomaszGasior** [comment]
Fajny pomysł, nie przyszedł mi do glowy.

**Comment by TomaszGasior** [comment]
Obecnie RDS RT jest tak dzielone!

**Comment by TomaszGasior** [comment]
Zaimplementowałem proponowaną zmianę w https://github.com/TomaszGasior/RadioLista-v3/commit/e53776c693a22a47e62a59fa3741e8ed607911b5 i https://github.com/TomaszGasior/RadioLista-v3/commit/96c44a86ebaf9947a4d6439b2640bd5ad4d5827c . Zmiana wejdzie zapewne w RadioLiście v3.8, ale nie wiem, kiedy będę wrzucal nową wersję na serwer. Być może w przyszłym tygodniu.
