### ISSUE TITLE
[Propozycja nowej funkcji] Dodawanie stacji OIRT

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#35]
Dzisiaj chciałem dodać sobie stację, którą odebrałem na OIRT. Częstotliwość 68.39. Niestety nie mogę jej dodać, ponieważ wykaz przyjmuje tylko wartości o końcówce np. 68.35 lub 68.40. Nalegam, aby taka zmiana pojawiła się jak najszybciej. Jeśli można dodać regułę, że stacje poniżej 74 MHz miały by odstępy co 0.01 MHz byłoby naprawdę świetnie. Nie trzeba od razu dawać takiego odstępu dla całego zakresu CCIR

- Wykazy i stacje radiowe (powiązane ze sobą): X

**Comment by TomaszGasior** [comment]
Duplikat: https://github.com/TomaszGasior/RadioLista-v3/issues/27

Oczywiście dzięki za głoszenie. Subskrybujcie zalinkowany wyżej wątek.

**Comment by TomaszGasior** [comment]
> Jeśli można dodać regułę, że stacje poniżej 74 MHz miały by odstępy co 0.01 MHz byłoby naprawdę świetnie.

Nie wiem, czy dam radę coś takiego zaimplementowac z  natywnymi widgetami przeglądarek,, ale spróbuję. Najwyżej zrobię 0,01 na stale.

**Comment by TomaszGasior** [comment]
Zaimplementowałem twoją sugestię. W zmianie https://github.com/TomaszGasior/RadioLista-v3/commit/3bd54ecf336c2baa24e02211b7b1e2d63ee68f4d zmieniłem domyślny krok pola częstotliwości na 0,01. Natomiast w zmianie https://github.com/TomaszGasior/RadioLista-v3/commit/d3b33db1ef512bab408bca8179700850e7b660e6 dla osób z włączonym JavaScriptem (czyli zapewne dla 99% ludzkości) dodałem logikę, która podnosi krok na 0,05 dla częstotliwości wyższych niż 74.

Zmiana wejdzie w RadioLiście v3.8. Może uda mi się ją wrzucić jutro na serwer.
