### ISSUE TITLE
[RDS RT] Spacje zamiast podkreślników 

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#37]
Myślę, że bardzo prosta funkcja. Mianowicie chodzi o zastępowanie podkreślników __ w RadioTexcie spacjami. Wielokrotnie kopiowałem sobie RT z tunera i musiałem usuwać podkreślniki. Funkcja na pewno poprawi wydajność podczas dodawania RadioTextu.

- Wykazy i stacje radiowe (powiązane ze sobą): X

**Comment by TomaszGasior** [comment]
Aktualny stan:
- w RDS RT podkreślniki nie są modyfikowane w ogóle;
- w RDS PS podkreślniki są zapisywanie do bazy danych, tak jak user je wpisze w formularzu edycji stacji, ale przy wyświetlaniu zostają zamienione na spacje.

Co proponujesz?
- Zamieniać podkreślniki na spacje i w RT, i w PS już przy zapisie tak, że po kliknięciu „Zapisz zmiany” w formularzu od razu następuje zamianać "_" -> " ".
- Zostawić w formularzu użytkownikowi tak, jak sobie wpisał, ale przy wyświetlaniu wykazu zamieniać "_" -> " ". 

Co byłoby bardziej intuicyjne twoim (waszym) zdaniem?

**Comment by HyperDX** [comment]
Druga opcja zdecydowanie lepsza. Takie samo rozwiązanie jest teraz w PS i jest to jak najbardziej w porządku :).

**Comment by TomaszGasior** [comment]
Jeszcze jedno. Czy są jakieś stacje, które rzeczywiście używają dosłownie podkreślnika w swoich PS-ach i komunikatach RT? Jeśli tak, czy warto przejmować sie tym przypadkiem?

**Comment by HyperDX** [comment]
Tak, ale pewnie jest ich niewiele. Złapałem 571 stacji (już nie wiem ile z RDS... o i propozycja nowej funkcji się kłania :) tylko Radio Centrum 106.4  nadaje taki RT: radioCENTRUM_106.4_ PIERWSZE_w_CENTRUM WYDARZEN. Więc raczej bym się nie przejmował tym i dodał taką funkcje.

**Comment by TomaszGasior** [comment]
Ok, postaram się zaimplementować w v3.9. Tę propozycję zgłoś oddzielnie, proszę. :)
