### ISSUE TITLE
Popup z tekstem komentarza jako opcja zamiast wypisywania całego tekstu komentarza 

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#41]
Proponuje skrócenie pola komentarz, zastępując komentarz ikonką (i) - po najechaniu na nią będzie wyświetlana treść komentarza tak jak ma to miejsce tu: [https://konrad.fmdx.pl/?q=2&id=744](url)
W związku z tym warto by było skrócić nazwę pola na "Koment.", "Kom." "Info".

- Wykazy i stacje: X

**Comment by TomaszGasior** [comment]
Jakoś nie za bardzo podoba mi się takie rozwiązanie — wolę, gdy komentarz jest widoczny tak jak teraz.

Natomiast warto się zastanowić, do czego w ogóle użytkownicy używają pola komentarza. Jeśli do, hmm, komentarza, to ma to sens i nie trzeba wtedy niczego chować. Natomiast problemem jest to, że w wielu wykazach użytkownicy używają komentarza do wpisania zawartości, które powinny znaleźć się po prostu w oddzielnej kolumnie wykazu, ale danej kolumny RLv3 nie oferuje.

Pozostawię to zgłoszenie otwarte, ale dopóki userzy używają pola komentarza niezgodnie z przeznaczeniem (bo muszą przez braki RLv3) to nie widzę takiej potrzeby.

**Comment by HyperDX** [comment]
Zawsze można pójść na kompromis i np. w ustawieniach wykazu zrobić pole ukrywania treści pola komentarz, które użytkownik może zaznaczyć lub odznaczyć. Takie ukrywanie może też zmniejszyć szerokość wykazu, dzięki temu może stać się bardziej przejrzysty.

**Comment by TomaszGasior** [comment]
Każda opcja konfiguracyjna ma swój koszt, bowiem aplikacja musi obsługiwać dwie formy wykonania tego samego zadania, a dodatkowo oferować użytkownikowi możliwość zmiany preferowanego zachowania. Innymi słowy: im mniej opcji konfiguracyjnych, tym łatwiej skupić się na jednym, z góry określonym, przewidywalnym zachowaniu.

Oddzielnym problemem jest a11y: musiałbym zakodować ewentualny popup tak, żeby był dostępny z poziomu klawiatury dla osób niepełnosprawnych ruchowo.

Nie jestem zdecydowanie przeciwko (dlatego trzymam to zgłoszenie otwarte), natomiast nadal nie widze sensu. Spróbuj proszę podać przykłady zastosowania takiej opcji, co taka opcja by wniosła, jakie problemy by rozwiązała, itp. Może wtedy będzie łatwiej znaleźć mi sens takiej personalizacji.

**Comment by HyperDX** [comment]
Przykład zastosowania na szybko. Długie komentarze, które mocno psują estetykę wykazu rozciągając jego wiersze np. tutaj [https://radiolista.pl/wykaz/190](url) Malutka ikonka z pop-upem i problem może być rozwiązany, a wykaz bardziej czytelny

**Comment by TomaszGasior** [comment]
@HyperDX Czy po zaimplementowaniu opcji https://github.com/TomaszGasior/RadioLista-v3/issues/21 (własna szerokość wykazu) problem wciąż jest aktualny i nadal potrzeba funkcji wyświetlania komentarza jako popup? Jeżeli tak, proszę cię o potwierdzenie — w miarę możliwości postaram się zająć tym ficzerem w najbliższy weekend.

**Comment by HyperDX** [comment]
Sądzę, że tak, nadal jest potrzeba implementacji takiej funkcji.
