### ISSUE TITLE
CKEditor does not work on Blink/WebKit-based browsers

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#43]
Editor is not visible. Editor's wrapper takes 100% of viewport width causing horizontal scrollbar. Reproduced with Google Chrome and Epiphany. Bug does not occur in Firefox.

![Zrzut ekranu z 2019-07-17 01-47-35](https://user-images.githubusercontent.com/1395027/61337319-39ebd280-a835-11e9-9467-ec6ba08f37ec.png)

**Comment by TomaszGasior** [comment]
Identical to https://github.com/TomaszGasior/RadioLista-v3/issues/33

**Comment by HyperDX** [comment]
Also this bug occur in Microsoft Edge

**Comment by TomaszGasior** [comment]
Temporarily solved on production by replacing current version of CKEditor with last version from RLv2. Very strange issue…

**Comment by TomaszGasior** [comment]
RLv3 uses custom build of CKEditor generated using automated generator from CKEditor website. Sometimes that generator produces ZIP archive with broken JS which does not work with Chrome (even when there was no CKEditor updates meanwhile!). It's completely strange for me but I'm not able to solve this problem because it's on CKEditor creators side.

For now I fixed main issue by regenerating CKEditor custom build on production server. I hope this issue won't happen again but I can't be sure
