### ISSUE TITLE
Dodawanie stacji z poziomu edytora

### ISSUE THREAD

**Issue by NightPurrer** [TomaszGasior/RadioLista-v3#49]
Gdy dodamy stację przechodzimy do jej edytowania, gdzie nie ma linku umożliwiającego dodanie kolejnej.
Aby to zrobić musimy wejść w wykaz i dopiero z jego poziomu kliknąć dodaj.
Jeśli link umożliwiający dodanie nowej stacji pojawi się w formularzu edycji już istniejącej, tworzenie wykazu będzie szybsze i wygodniejsze. :)
- Wykazy i stacje:
- Ogólne działanie i wygląd serwisu:

**Comment by TomaszGasior** [comment]
Dziękuję za sugestię. Masz rację, dodawanie nowej stacji z poziomu edycji istniejącej stacji jest pożyteczne — nie pomyślałem o tym.

W commicie https://github.com/TomaszGasior/RadioLista-v3/commit/4f934658d9d9cb6ca3cdde1902007e29c677c810 dodałem pozycję „dodaj stację” do menu górnego ekranu edycji stacji. Ze względu na to, że dotychczas były tam już trzy elementy i dodanie kolejnego zaburzyłoby estetykę i czytelność całego menu, w zamian za to usunąłem pozycję „usuń tę stację”.

Od teraz, aby usunąć dodaną stację, trzeba się będzie udać do ustawień wykazu i tam kliknąć „usuń stacje lub wykaz”. Teoretycznie może to pogorszyć komfort usuwania stacji z wykazu, ale w praktyce wydaje mi się to małym problemem, bo według statystyk jedynie <5% wejść na stronach RadioListy jest na stronie usuwania wykazu/stacji.

**Oczywiście jestem zainteresowany waszym zdaniem i jestem skłonny przywrócić usuniętą pozycję menu, jeśli uważacie ją za bardzo ważną, kosztem czytelności i estetyki całego menu na ekranie edycji stacji.**
