### ISSUE TITLE
Wsparcie dla wykazów DAB+

### ISSUE THREAD

**Issue by SzymonDX** [TomaszGasior/RadioLista-v3#50]
Proponuję dostosowanie Radiolisty pod wykazy cyfrowego radia (DAB+).

Aktualnie brakuje kolumny ‘kanał’ (w DABie kanał odbioru podaje się na równi z częstotliwością). 
Myślę, że warto zrezygnować z zaokrąglania liczbowego przy częstotliwości (aktualnie z częstotliwości 202,928 MHz robi się 202,95 MHz). 
Dodatkowo przydałoby się pole ‘lista kanałów’, aby wpisać kanały dostępne w danym multipleksie DAB+ - w sumie mogłoby to wyglądać jak obecnie kolumna z RDSem.

Uważam, że dobrym pomysłem jest stworzenie wyboru typu wykazu – domyślnie FM, z możliwością wyboru np. DAB+ / AM / TV. A to dlatego, że część kolumn między tymi pasmami będzie się różnić, stąd przy późniejszej rozbudowie wykazu wrzucanie wszystkich kolumn do jednego worka nie ma raczej sensu. Przejrzystość interfejsu również na tym zyska.

- Wykazy i stacje: X
- Ogólne działanie i wygląd serwisu: X

**Comment by TomaszGasior** [comment]
Czy mógłbym cię prosić o podanie linków do przykładowych wykazów DAB+, abym mógł sobie zobaczyć jak one wyglądają?

**Comment by HyperDX** [comment]
@TomaszGasior Ciężko jest znaleźć tropo-logi DXerów w paśmie DAB+, a troszkę już szukałem. Jak na razie jeśli chodzi o wykaz wszystkich emisji to jest na przykład ten: [http://radiopolska.pl/wykaz/dab](url), który mniej więcej pokazuje jak powinien wyglądać rozkład elementów w wykazie dla tego pasma.

**Comment by TomaszGasior** [comment]
@HyperDX  

Wydaje mi się, że źle umieszczasz odnośniki w formacie Markdown i tam, gdzie powinien być tekst linka, wklejasz adres, a tam gdzie ma być adres, zostawiasz domyślne — dlatego twoich linków nigdy nie da się kliknąć. Możesz je po prostu luzem wkleić do treści: wtedy automatycznie będą klikalne.

---

@SzymonDX 

> Myślę, że warto zrezygnować z zaokrąglania liczbowego przy częstotliwości (aktualnie z częstotliwości 202,928 MHz robi się 202,95 MHz).

Możemy zastosować rozwiązanie użyte w polu mocy nadajnika: przy wyświetlaniu wartości są używane co najmniej dwa miejsca po przecinku, ale opcjonalnie jest możliwość wprowadzenia trzeciego miejsca po przecinku. Będzie takie coś pasowało? Jeśli tak, bardzo proszę o założenie oddzielnego zgłoszenia dla tego problemu.

> Dodatkowo przydałoby się pole ‘lista kanałów’, aby wpisać kanały dostępne w danym multipleksie DAB+ - w sumie mogłoby to wyglądać jak obecnie kolumna z RDSem.

Mamy dwa podejścia:
- Podejście A: wykazy zawierające stacje radiowe, których cechą jest m.in. to, na jakim multipleksie dana stacja się znajduje.
- Podejście B: wykazy zawierające multipleksy, których cechą jest m.in. jakie stacje radiowe zawiera dany multipleks.

Mam wrażenie, że obydwa podejścia mają sens i mogą być pożyteczne dla użytkowników. Można je połączyć w jednym serwisie, nie wykluczają się, natomiast trzeba to zrobić z głową. Od samego początku w 2012 roku design RadioListy opiera się na tym, że w wykazach znajdują się **stacje radiowe** (lub z delikatnym naciąganiem, także TV). Gdybym teraz tak po prostu do pola obiektu „stacja radiowa” dodał pole „lista kanałów” to będzie to kompletnie bez sensu z perspektywy designu serwisu: no bo jak stacja może zawierać stacje? Gdy natomiast do obiektu „stacja radiowa” dodam pole „multipleks” to będzie to miało sens.

To, co chce powiedzieć to to, że obydwa podejścia mają sens i są wykonalne, natomiast podejście A „dodawajmy każdą stację oddzielnie, wpisując na którym jest MUX-ie” (z możliwością posortowania po MUX-ach) będzie bardziej pasować do obecnej konstrukcji serwisu oraz będzie po prostu prostsze i szybsze dla mnie do zrobienia. Przekonstruowanie całej architektury serwisu tak, by dało się zrobić oddzielny typ wykazu z MUX-ami, a nie stacjami, wymagać będzie więcej pracy. Nie wiem, czy będę w stanie czasowo zrealizować coś takiego. 

Poza tym warto jest po prostu konceptualnie oddzielić te podejścia. Dlatego bardzo proszę, wskaż mi tutaj na którym z tych dwóch podejść chciałbyś żebyśmy się skupili, a dla tego drugiego możemy ew. zrobić oddzielny wątek. Możemy np. zrobić tak, że w tym wątku skupimy się na podejściu A, natomiast możemy zrobić oddzielny wątek dla podejścia B, w którym razem: ty z perspektywy usera, ja z perspektywy programisty, opiszemy jak to podejście należy zrealizować i jeśli ktoś w przyszłości będzie chciał poświęcić na to czas, będzie mógł posłużyć się tymi pomysłami.

RadioLista jest open source właśnie po to, żeby oprócz mnie serwisem mogły zajmować się też inne osoby, które mają na to ochotę, dlatego takie rozpisanie i podzielenie pomysłów ma dużo sensu nawet, jeśli nie mogę obiecać, że ja coś zrealizuję we własnym czasie. Tak działa open source. 

(Tak przy okazji. Te zgłoszenia, które „przypisuję” do siebie tzn. we właściwościach zgłoszenia po prawej w polu „Assignees” widać mój nick, to te zgłoszenia, w których deklaruję, że postaram się je zrealizować w najbliższym czasie i zostawiam je dla siebie. Te, które takiej „przypinki” nie mają i/lub mają etykietkę „help needed” są zostawione dla innych zainteresowanych — choć oczywiście w dalszej przyszłości mogę się sam do nich przypisać z powrotem. :) )

> Uważam, że dobrym pomysłem jest stworzenie wyboru typu wykazu – domyślnie FM, z możliwością wyboru np. DAB+ / AM / TV

Będę bardzo wdzięczny, jeśli założysz kolejny oddzielny wątek, w którym opiszesz, jak to dokładnie mogłoby wyglądać. Na przykład wypiszesz wszystkie rodzaje wykazów i dokładnie czym mają się różnic z twojej perspektywy, z perspektywy użytkownika. :)

**Comment by TomaszGasior** [comment]
Dla typu wykazów założylem zgloszenie #120 
Dla kanału założyłem zgłoszenie #122 

@SzymonDX @HyperDX Proszę was o pomoc. Będę wdzięczny za opisanie w #122 jaka jest dokładna specyfikacja kolumny kanału — czy zawiera cyfry, liczby, jaki zakres, ile znaków. Proszę też o pomoc w zadaniu #121: jakie byście widzieli predefiniowane „zestawy” kolumn wykazu pod konkretne zastosowania?

**Comment by TomaszGasior** [comment]
To zadanie zamykam, jako że spełniło swoje zadanie. @SzymonDX Możesz zasubskrybować zalinkowane wyżej taski, żeby być na bieżąco z postępem.
