### ISSUE TITLE
Uwzględnianie przekreślenia w łącznej ilości stacji (Liczba stacji)

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#51]
**Opis błędu:**
Problem polega na tym, że gdy jakaś stacja zmieniła parametry nadawcze, zmieniła się jej nazwa itd. (ale wciąż nadaje i ją odbieram) dublowałem ją i nieaktualną przekreślałem. Zauważyłem też, że te przekreślone stacje są zliczane i dlatego na samym dole "Liczba stacji" była myląca. Proszę o modyfikację, aby stacje przekreślone nie były liczone i wyświetlane w "Liczba stacji"

**Informacje o oprogramowaniu:**
- System operacyjny: nie dotyczy
- Przeglądarka: nie dotyczy
- Używane urządzenie: nie dotyczy

**Comment by TomaszGasior** [comment]
@SzymonDX , @HyperDX Dziękuję za wasze propozycje. Niestety, na razie nie ustosunkuję się do nich, gdyż jestem zajęty innymi sprawami. Nad RadioListą będę ponownie pracował może dopiero pod koniec roku lub w przyszłym roku. Proszę o cierpliwość.

**Comment by TomaszGasior** [comment]
Z perspektywy aplikacji RadioLista oznaczenie stacji markerem „przekreślenie” nie ma żadnej semantyki, tj. nie ma żadnego powodu, aby RL nie zliczała stacji przekreślonych. Zmieniam status zgłoszenia z „bug” na „enhancement”.
