### ISSUE TITLE
Add radiostation field: mode/stability

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/RadioLista-v3#6]
for consideration

RadioStation::$stability with possible values:
- tropo
- stable

http://forum.radiopolska.pl/index.php?showtopic=20778&view=findpost&p=246629

**Comment by TomaszGasior** [comment]
User comment:

> Tropo (ducting), odbiór stały (regular), scatter

**Comment by TomaszGasior** [comment]
Possible values:

- stable
- tropo
- scatter
- sporadic-e

**Comment by TomaszGasior** [comment]
Polish name: Typ odbioru

**Comment by TomaszGasior** [comment]
Proper Polish label of possible values, user suggestion

> 1. jonosferyczny (sporadic E)
>2. troposferyczny (tropo)
>3. odbity (scatter)
>4. stabilny (regular),

**Comment by TomaszGasior** [comment]
Implemented in https://github.com/TomaszGasior/RadioLista-v3/commit/7acc48a81aff9e2ce852a752fd1b26fb943d81fb.  @HyperDX, @SzymonDX , what do you think about these screenshots?

![Zrzut ekranu z 2019-07-19 03-50-05](https://user-images.githubusercontent.com/1395027/61504135-989e8100-a9da-11e9-8448-7afeaf4dd032.png)

![Zrzut ekranu z 2019-07-19 03-50-42](https://user-images.githubusercontent.com/1395027/61504141-9cca9e80-a9da-11e9-937e-1fbeb1526c33.png)

**Comment by HyperDX** [comment]
Wszystko ok, ale jakoś nie pasuje mi to stabilny, może na liście być, ale moim zdaniem ja bym wolał aby w wykazie (chociaż w moim jak reszta się nie zgodzi i jakby się tak ewentualnie dało) wyświetlało się jako regular. Po prostu to mi bardziej odpowiada ;)

**Comment by TomaszGasior** [comment]
@HyperDX a może być „regularny” zamiast „regular”, bo mój językowy pedancik się wścieknie? :P

**Comment by HyperDX** [comment]
@TomaszGasior Ok :D zawsze jest to jakiś kompromis ;)
