### ISSUE TITLE
Błędna data w "Ostatnio zmodyfikowanych wykazach"

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#65]
**Opis błędu:**
Błąd polega na tym, że osoby, które zmodyfikowały wykaz dziś (tj. 30-12-2019) mają błędnie wyświetlaną datę na stronie głównej RL - dokładnie rok, a jest to 30 grudnia 2020
[https://i.imgur.com/SSlabDo.png](url) <-- można zobaczyć to na tym zdjęciu

Błąd występuje na wszystkich urządzeniach bez względu na ich system operacyjny i przeglądarki.

**Comment by TomaszGasior** [comment]
Dziękuję za informację! W https://github.com/TomaszGasior/RadioLista-v3/commit/35060576415a744c8e2eeea42c4a1aa169309729 naniosłem poprawkę. Wrzucę ją na serwer produkcyjny przy najbliższej aktualizacji, być może w ciągu kilkunastu dni. Tutaj wyjaśnienie, co takiego magicznego się stało: https://www.youtube.com/watch?v=D3jxx8Yyw1c .
