### ISSUE TITLE
Etykiety kolumn

### ISSUE THREAD

**Issue by HyperDX** [TomaszGasior/RadioLista-v3#88]
**Opis nowej funkcji lub proponowanej zmiany:**
Prosta funkcja dodająca etykiety (pop-up) do kolumn widocznych na samej górze wykazu. Etykiety oczywiście będą widoczne po najechaniu na nazwę danej kolumny. 
**Propozycja** zawartości etykiet:

MHz - częstotliwość odbieranej stacji
Pol. - polaryzacja danej emisji (pionowa/pozioma/kołowa/mieszana)
Nazwa - nazwa stacji radiowej
Kraj - kraj z którego odebrana została stacja
Lokalizacja - lokalizacja obiektu nadawczego
kW - moc ERP wyrażona w kW
Jakość - jakość odbioru rozgłośni (1-5)
RDS - Dane RDS (PS/PTY/RT)
PI - Programme Identification, heksadecymalny kod identyfikujący stację radiową
km - QRB, odległość od obiektu nadawczego w kilometrach
1 odbiór - data pierwszego odbioru stacji.
Odbiór - sposób odbioru danej stacji (tropo/scatter/sporadic-e/regular)
Odn. - odnośnik ukazujący odbiór stacji radiowej.

Oczywiście zawartość może być inna, to tylko moja wymyślona na szybko propozycja. Myślę, że znacznie ułatwiłoby to zwłaszcza początkującym poznanie "co jest czym", bo kolumny: km, kW, Pol. itd. mogą być dla niektórych niezrozumiałe.  Również warto rozważyć dodanie takich etykiet do przyszłej anglojęzycznej wersji wykazu: (przykład tu: https://konrad.fmdx.pl/).

**Czego ma dotyczyć twoja propozycja?**

- Wykazy i stacje: X
- Konta użytkowników:
- Ogólne działanie i wygląd serwisu: X

**Comment by TomaszGasior** [comment]
Dziękuję za sugestię. Od dawna od tym myślę, bowiem to, co napisałeś jest już zaplanowane tutaj: #15, choć etykieta tego zgłoszenia mogla być dla ciebie myląca.

**Comment by TomaszGasior** [comment]
@HyperDX 

W zmianie https://github.com/TomaszGasior/RadioLista-v3/commit/2cbdd6e633696f7125fee68fc2dd67d52319992a zaimplementowałem zaproponowaną przez ciebie zmianę.

Każda kolumna w RadioLiście ma dwie nazwy: nazwę wyświetlaną i nazwę nagłówkową. Ta druga jest używana tylko w nagłówkach tabeli wykazu, ta pierwsza zaś w całej reszcie interfejsu serwisu — w ustawieniach widoczności i kolejności kolumn w wykazie oraz w formularzu dodawania i edycji stacji. Dokładnie ta sama nazwa wyświetlana od v3.23 będzie również używana jako wartość popup nagłówka kolumny, jeśli zawartość nagłówka kolumny nie jest dokładnie taka sama. 

Jeżeli masz taką ochotę, możesz rzucić okiem do zalinkowanych poniżej plików językowych i ew. zaproponować jakieś zmiany. W bloku `heading` są nazwy nagłówkowe, a bloku `column` są nazwy używane wspólnie w pozostałych częściach serwisu (i należy wziąć to pod uwagę przy ich zmianie).

- Polski: https://github.com/TomaszGasior/RadioLista-v3/blob/master/translations/radio_table.pl.yaml
- English: https://github.com/TomaszGasior/RadioLista-v3/blob/master/translations/radio_table.en.yaml

**Comment by HyperDX** [comment]
Dziękuję. Na razie nie mam uwag odnośnie opisów zarówno w języku polskim jak i w angielskim. ;)
