### ISSUE TITLE
Liczba stacji przy dacie aktualizacji

### ISSUE THREAD

**Issue by NightPurrer** [TomaszGasior/RadioLista-v3#96]
Obecnie w sekcji ostatnio aktualizowane wykazy nie wyświetla się liczba stacji w wykazie przy dacie. Proponuję dodać taką informacje, gdyż może być ona przydatna.

**Comment by TomaszGasior** [comment]
Miło mi cię tu widzieć. Mówisz o stronie głównej? Postaram się!

**Comment by TomaszGasior** [comment]
W miarę możlwiości staraj się używać szablonów przy tworzeniu zgłoszeń. :)

**Comment by TomaszGasior** [comment]
@NightPurrer Po pewnym przemyśleniu tej sprawy doszedłem do wniosku, że nie chcę dodawać liczby stacji do pozycji na liście ostatnio utworzonych oraz ostatnio aktualizowanych wykazów. 

Moje uzasadnienie jest następujące: głównym celem listy ostatnio dodanych/zmodyfikowanych wykazów jest wyszczególnienie wykazów względem daty ich modyfikacji lub utworzenia, a nie względem ich objętości, tj. ile mają stacji. Dodanie do obecnie wyświetlanych tytułu i daty modyfikacji/utworzenia kolejnych dodatkowych metadanych, takich jak liczba stacji, zaburzy design i czytelność tych list. Strona główna RadioListy w moim odczuciu ma pełnić rolę wskaźnika, że tak powiem, „życia serwisu”: tj. tego, co aktualnie robią użytkownicy, co się dzieje: ma być lekka i nieprzeładowana informacjami.

Zgadzam się z tobą z 100%, że możliwość przejrzenia wykazów względem liczby stacji jest bardzo użyteczna. Z tym, że RadioLista wielu lat taką funkcję posiada! :) Na samym dole strony (ostatni lub przedostatni link w layoucie strony) znajduje się odnośnik o nazwie „Wszystkie wykazy” kierujący do podstrony „Wszystkie wykazy RadioListy”, gdzie na jednej wielkiej stronie są wylistowane wszystkie wykazy publiczne, posortowane domyślnie właśnie według liczby stacji (malejąco). Podstrona ta umożliwia również posortowanie wg jednostki (kHZ vs MHz) i daty aktualizacji.
